def show_help():
    print("═" * 50)
    print("  DailyDriver — Quick Reference")
    print("═" * 50)
    print()

    # ── Logging ──
    print("📝 Logging")
    print("  p [time/offset]")
    print("     Log a prayer (Enter confirms)")
    print("     p          → current slot")
    print("     p -15      → 15m before fixed time")
    print("     p 05:30    → explicitly at 05:30")
    print()
    print("  s <sleep> <wake>")
    print("     Log sleep duration")
    print("     s 23:00 07:15")
    print("     s 23-7:15  (compact form)")
    print("     s n 08:00  (n = now)")
    print()
    print("  Any other text = free‑form journal")
    print("     worked on project 9-12")
    print()

    # ── Prayer management ──
    print("🕌 Prayer Management")
    print("  rq")
    print("     Mark missing prayer as qada")
    print("  mp")
    print("     Mark missing as missed or qada")
    print()

    # ── Events ──
    print("⏱ Events (start / end / cancel)")
    print("  se")
    print("     Start a running event timer")
    print("  ee [text]")
    print("     End event & log entry")
    print("     ee finished report")
    print("  ce")
    print("     Cancel the running event")
    print()

    # ── Chaining ──
    print("🔗 Chaining")
    print("  ln [text]")
    print("     Log entry from last action")
    print("     to now")
    print("     ln replied to emails")
    print()

    # ── Viewing ──
    print("👁 Viewing & Summaries")
    print("  today")
    print("     Show everything logged today")
    print("  view [filter]")
    print("     Browse entries (n=next p=prev)")
    print("     view project")
    print("     Inside view: id=edit entry")
    print("  stats")
    print("     Prayer/sleep/hygiene stats")
    print()

    # ── Tools ──
    print("⚙ Tools & Configuration")
    print("  bd [name date]")
    print("     Add birthday (Jalali)")
    print("     bd Ali 1386/05/12")
    print("     bd Zahra 5/12")
    print("  t [description]")
    print("     Add intention / to‑do")
    print("     t finish report")
    print("  hygiene")
    print("     Manage hygiene intervals")
    print("  flags")
    print("     Manage flags (tags)")
    print()

    # ── Multi‑line ──
    print("📄 Multi‑line entries")
    print("  :m")
    print("     Start collecting lines")
    print("  ---")
    print("     (alone) End & log collected lines")
    print()

    # ── Other ──
    print("❓ Other")
    print("  ?          This help")
    print("  q          Quit")
    print()
