[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dailydriver"
version = "1.5.0"
description = "Personal terminal‑based life tracker (prayer, sleep, journal, calendar, search)"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "jdatetime",
    "hijridate",
    "porter2stemmer",
]

[project.scripts]
daily = "dailydriver.cli.commander:repl"

[tool.setuptools.packages.find]
include = ["dailydriver*"]

[tool.ruff]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
